### ISSUE TITLE
fastapiに関するエラーの解決方法について

### ISSUE THREAD

**Issue by Kusunoki9999** [ItisNoMatter/cist-cat#20]
## 達成したいことは何ですか

ModuleNotFoundError: No module named 'fastapi'のエラーコードが出ないようにしたいです

## 不具合発生までの手順

以下の手順を行いました。  

1.main.pyを編集しようとした際、波線を発見
2.環境構築で何らかの不備があったかと思い至る（そもそもこの考えが違うかも？）

以下のような状況です

![スクリーンショット (61)](https://user-images.githubusercontent.com/105924969/222007472-ce0d9159-c99e-457b-b87c-c5b089681a11.png)

原因を確かめるため、以下のようなテストを行ってみましたが、
問題の解決には至りませんでした。

(a) コマンドプロンプトでルートディレクトリにてpip install fastapiのコマンドの入力を行った(参考サイト：https://bobbyhadz.com/blog/python-no-module-named-fastapi)
⇒変化なし

(b) vscodeでPythonのバージョンを確認（参考サイト：https://stackoverflow.com/questions/71113116/modulenotfounderror-no-module-named-fastapi）
⇒解決せず

どうかアドバイスのほど、よろしくお願いいたします。

**Comment by 618knot** [comment]
もともと用意されていたdevcontainerやDocker周りに不備がありそうです〜(@ItisNoMatter お願いします)

今できそうなことは、コンソールで`pip list`コマンドを叩いてみてFastAPIなど`requirements.txt`に記述されているライブラリが入っているか確認してみるくらいですかね？

**Comment by ItisNoMatter** [comment]
## 本題
送っていただいたスクリーンショットの状態では、dev container環境に入れていません。
画面左下緑色の[WSL Ubuntu]をクリックし、[Reopen in Container]を選択してdev container環境に入ってください（初回は時間がかかります）。

成功すると添付画像のように、画面左下に[Dev Container:python3]と表示されます。
![main py - cist-cat  Dev Container_ Python 3  - Visual Studio Code 2023_03_01 17_16_30](https://user-images.githubusercontent.com/41831807/222082515-2f5c8e16-4be9-4855-86b1-552f3ab9d697.png)

## 捕捉
スクリーンショットを見るに、@Kusunoki9999 さんのVScodeが開いていたのは、WSL直下のpython環境です。WSL環境はWindows環境とは隔離されています。
ですから、コマンドプロンプトを使ってWindows環境にpip installしても、WSL環境のpythonを参照しているVScode上には影響がなかったのだろうと思います。

WSLターミナル上でpip installなどをしても問題は解決できますが、dev containerに入るほうが根本的な解決になります。

**Comment by Kusunoki9999** [comment]
@ItisNoMatter さんの示してくれた手順で対応した結果、fastapiに関するエラーは出なくなりました。 お二方とも対応して下さってありがとうございました！
その一方で本問題解決直後、"Pylance"拡張機能がアクティブ化できない、という旨のエラーメッセージが表示されました。こちらに関しては現段階で気にしなくてもよいものでしょうか？

![スクリーンショット (69)](https://user-images.githubusercontent.com/105924969/222330000-68092937-e0a9-44e5-95c8-958b3d8706b2.png)

**Comment by ItisNoMatter** [comment]
本題が解決されてよかったです
拡張機能に関して、pylanceは無効なままでも一応開発を続けることはできるので現状気にしなくても大丈夫です（強力なエディタアシストは受けられなくなります）。
気にしない場合、このIssueをcloseしてください。

気にしたいのであれば、VScode画面左のタブにある「拡張機能」を開いて[Python][Pylance]項目を確認したいです。
そこで解決策(再読み込みなど)がVScodeから提案されていることもあります。

**Comment by Kusunoki9999** [comment]
pylanceの問題に関しても解決しました！
拡張機能を確認したところ、"python"がアンインストールされていました(なぜかは不明)
再度インストールを行いました。

改めて対応いただきありがとうございました！このissueをcloseさせていただきます。
