### ISSUE TITLE
curl(7): Connection refusedの対処法

### ISSUE THREAD

**Issue by Kusunoki9999** [ItisNoMatter/cist-cat#23]
## 達成したいことは何ですか

ターミナルでcurl localhost:9000/をたたいた際、期待したレスポンスが返ってくるようにしたいです。

## 不具合発生までの手順

以下の手順を行いました。  

1.main.pyに編集を加え、git add とgit commit を行いました。
![スクリーンショット (75)](https://user-images.githubusercontent.com/105924969/222768004-210582de-d49b-4e2b-9431-d802348167a6.png)

2.コマンドプロンプトで curl kocalhost:9000/ を叩きました。

その結果、下のエラーメッセージが表示されました。
![image](https://user-images.githubusercontent.com/105924969/222768722-3bc78cd9-7568-4b81-90c3-e4527302f789.png)

原因を探るべく、ポートの通信を確認してみました。以下のスクショです。
![スクリーンショット (77)](https://user-images.githubusercontent.com/105924969/222771956-f46c0f9e-dc83-402e-b4ba-79720ae3454a.png)

原因として以下のが考えられますが、自らでは対応に限界がありました。

開発対象が起動できていない。（参考サイト：https://teratail.com/questions/126920）
⇒何をもってしての”起動”なのかが分かりませんでした。

**Comment by 618knot** [comment]
# 応急処置
devcontainer周りの知識がないので力及ばずで申し訳ありませんが、とりあえず最低限APIを起動した状態までもっていく方法を紹介します(不足部分は @ItisNoMatter に任せます。僕もわからない)

## 状況

> 開発対象が起動できていない。

おそらくdevcontainerに入った段階ではFastAPIが起動していません(本来はdevcontainerに入った時点で起動コマンドが走っていてほしいはず..?)。
つまり、起動していない(ポート開放していない)状態でリクエストを送っても当然何も返ってきません。

## 一時的な対応
一時的な対応としてAPIを手動で起動します。
以下の操作はVSCodeのターミナル(貼ってくれている画像1枚目のところ)で行ってください。
1. `cd bff`( `main.py` がある `bff` フォルダへ移動します)
2. `uvicorn main:app --reload --host 0.0.0.0 --port 9000`(9000ポートを指定してFastAPI起動コマンドを叩きます)
![image](https://user-images.githubusercontent.com/82982400/222871238-f4940a5a-ca0f-48b7-8270-0f6a3cd0d124.png)
これでAPIが起動できたので
`curl localhost:9000/`でレスポンスが返ってくるはずです。

## 雑談
- 参考サイトのURLについて
    -  閉じ括弧がURL判定されてしまってよくわからないところに飛ばされます。[こんな感じ](https://teratail.com/questions/126920)でリンクを貼れると事故が減りそうです
    `[こんな感じ](https://teratail.com/questions/126920)`
    ![sdfdsfsd](https://user-images.githubusercontent.com/82982400/222872137-43f3bfe8-0f39-4bcc-9a66-fd8d3fdd8f5e.png)

- issueの紐づけについて
    -  せっかくGithub上でやり取りをしているのでGithubの機能を使ってみましょう。
    例えば、今回のような質問をするときは自分の手持ちissueと紐づけてあげると質問者がどこのissueで詰まっているのかが分かりやすいです。
    @Kusunoki9999 さんがいまアサインしているissueは12番ですから、 #12 このように質問の冒頭にでも書いておくといい感じです。
    ` #12 ` ←issueの紐づけはこれを書くだけでできます。

**Comment by Kusunoki9999** [comment]
本問題に関してひとまず解決(?)したので、その経緯を以下に示します。

### 経緯
1, @618knot さんが示してくれた応急処置の手順を試し、APIを問題なく起動。
2,ターミナルで`curl localhost:9000`を叩くものの、最初同様のエラーメッセージが表示。
3,それから10分ほど経った後、突如vscodeに｢localhost:9000に接続しますか？｣的なウィンドウが表示されたので、OKを押す（スクショ撮り忘れました、すみません）
4,localhost:9000が開かれる。
![スクリーンショット (83)](https://user-images.githubusercontent.com/105924969/222876352-9191aaa8-60c4-45ee-9909-748ad7600f59.png)

### ｢雑談｣について
URLの貼り付けとissueの紐付けについて承知しました。次回以降の参考にしたいと思います。
ありがとうございます！

**Comment by ItisNoMatter** [comment]
対応遅れました
@618knot 対応感謝です

dev containerの起動時にdocker compose buildが走らないのは、現段階の仕様としては正常です（手動でdocker compose を叩く想定でした）
ただ指摘の通り、開発環境起動時にAPIサーバー諸々が起動してほしいというのはもっともだと思うので別issueを立てて対応します。

**Comment by Kusunoki9999** [comment]
了解しました。お二人ともありがとうございます。
