### ISSUE TITLE
Neumophismを使うためのライブラリを導入したので動作確認

### ISSUE THREAD

**Issue by katatsumr** [ItisNoMatter/cist-cat#26]
## 簡単な動作確認の仕方

Neumophismを使うためのライブラリを導入したので動作確認がしたいです。

## 不具合発生までの手順

以下の手順を行いました。  

1.Androidエミュレーターの起動

その結果、以下のような結果になりました

エミュレータ―の画面が初期状態のままです。
テストの画面を用意しなければいけないのかな、と思いましたがどのフォルダに何を作ればいいのか分かりません。

**Comment by ItisNoMatter** [comment]
エミュレータを起動したのち、アプリケーションの実行をする必要があります。

まず、app/src/main/java/com/example/cist_cat/MainActivity.kt を開き、画面上部の実行ボタン(画像強調部分)を押し、「app」を実行して下さい。

![無題のプレゼンテーション - Google スライド - Google Chrome 2023_03_06 20_27_27](https://user-images.githubusercontent.com/41831807/223099670-d43c371f-1d73-4992-909d-e1eafec72672.png)

成功していれば、以下のようになります
![CIST-CaT – MainActivity kt  CIST-CaT app main  2023_03_06 20_34_11](https://user-images.githubusercontent.com/41831807/223099136-82bda00a-d670-4285-aca9-345a91d6c770.png)
54ea09.png)

エミュレータでappの実行ができたら、次は以下の作業を期待しています。
1. MainActivity.ktファイルに、[composableな関数]として(https://developer.android.com/jetpack/compose/tutorial?hl=ja#define-a-composable-function)NeumophismSample()を定義する
2. MainActivity.kt内でLogo()を呼んでいる部分を代わりにNeumophismSample()に置き換える
3. もういちどappを実行し、スクリーンショットを撮る

1のNeumophismSample()内の記述は、[ライブラリのREADME](https://github.com/CuriousNikhil/neumorphic-compose)を参考にしてほしいです。
わからないことがあればまた追記してください。

**Comment by Reo-Satooooo** [comment]
@ItisNoMatter 
このissueはフロント側のものなのでクローズして大丈夫かな？
