### ISSUE TITLE
バス時刻表PDFファイルの取得

### ISSUE THREAD

**Issue by 618knot** [ItisNoMatter/cist-cat#27]
**概要**
[大学ホームページ](https://www.chitose.ac.jp/info/access)に置かれている時刻表PDFをダウンロードしてくる方法を検討し、実装する
**目的**
バス時刻の情報を取得するため
**TODO**
1. PDFのダウンロード方法を検討する
2. 検討した方法でtimetable-parserサブモジュールに実装する
3. 動作確認する

**Comment by ItisNoMatter** [comment]
@Reo-Satooooo 
どういう風に実装進めるイメージですか？
（サブモジュールへのpush権限が必要なのかな、と思いました）

**Comment by Reo-Satooooo** [comment]
@ItisNoMatter 
一旦、PDFをダウンロードしてローカルのファイルとしてデータを保持できるようにする部分までの実装を目指してる。
とりあえずbffのディレクトリ内にまとまった単位でロジックをクラスに分けて実装中です。
（サブモジュールには現在実装中のロジックが出来てからリファクタリングを兼ねてみんなで検討した上で移植するのが良いかと思ってました。）

**Comment by ItisNoMatter** [comment]
@Reo-Satooooo 
了解です！よろしくお願いします

**Comment by Reo-Satooooo** [comment]
@ItisNoMatter @618knot 
進捗報告
1. WebのPDFファイルをローカル環境内にダウンロード完了（ただし、ファイル名の動的な変化に対応する必要あり）
2. ローカルのPDFかたテキストデータとして時刻表を抽出←イマココ（扱いやすい形式で上手く抽出できていない）
3. 抽出したデータをjson形式へ変形する

**Comment by ItisNoMatter** [comment]
@Reo-Satooooo 
ありがとうございます！！コードめちゃくちゃ読みやすくて助かります。
## このissueの債務について
```  ローカルのPDFからテキストデータとして時刻表を抽出 ``` 以降について、pdfからのデータ抽出機能、jsonへの変換機能は現状の[timetable-parserモジュール](https://github.com/618knot/timetable-parser/tree/85facbf65778b0221a6fa659d307afa39c23582b)に動くものが実装されているという認識です。つまり、新しくそのへんの処理を書く必要はないと思います（このissueの責務はファイルの取得までです）。
追加で、timetable-parserは現状downloadディレクトリの0番目のファイルを参照するので、「ファイル名の動的な変化への対応」についても追加でコーディングする必要はなく、ディレクトリにpdfファイルを置くだけで動くだろうとも思っています。

## 今後のタスク
現状、つぎのどちらかによってこのissueをcloseできそう、と僕は思っています
1. 現状のダウンロード処理をtimetable-parserモジュールに移植し、保存先のディレクトリを調整
2. timetable-parser側に、bffからpdfを渡せるようにする

どちらにせよ、timetable-parserの中身を弄る必要があるはずなので、@618knot の意見を聞きたいです。

## 謝罪
このへんのいざこざは、開発初期の設計段階でpdfファイルの保持責務を負うのがどのモジュールなのかはっきりしていないことが原因で起こっています、すみません！！

**Comment by Reo-Satooooo** [comment]
@ItisNoMatter 
現状理解しました！

以下の判断のためにtimetable-parserモジュールへのpush権限が欲しいです
> 1.現状のダウンロード処理をtimetable-parserモジュールに移植し、保存先のディレクトリを調整
> 2.timetable-parser側に、bffからpdfを渡せるようにする

モジュールの中身を確認して @618knot とも一緒に協議した上で判断しましょう
