### ISSUE TITLE
pdf-parserから受け取ったデータを整形する関数の実装

### ISSUE THREAD

**Issue by ItisNoMatter** [ItisNoMatter/cist-cat#29]
# 概要
pdf-parserのAPIが返すjson形式と、フロント側が期待しているjson形式は現状異なります。(ここでいう期待しているjson形式とは、[dummy_sheet.jsonと同じ形式のもの](https://github.com/ItisNoMatter/cist-cat/blob/develop/bff/dummy_sheet.json)を指します)
pdf-parserが返す形式のデータを加工し、フロントが期待しているjson形式に整形する機能を持った関数を作成してください。

# 目的
フロントが直接pdf-parserのAPIを叩かないのは、もし今後pdf-parserの仕様が変わってもフロント側がそれを気にせず扱えるようにするためです。
フロントエンドとバックエンドの分離をするために、BFFでこのような処理を行なっています。

# TODO
1.  pdf-parserが返すjsonのダミーを入手or作成する
2. format_json関数を定義　引数に加工前のjsonをとり、加工済jsonを返す
3. テスト用の関数を定義　format_jsonの引数に1.で入手したjsonを渡し、戻り値をprintするだけ(本当はちゃんとテストコード書いた方がいい)
4.  加工処理を頑張って書く
5.  テスト用の関数を実行して、期待した結果になっているか確認する。

**Comment by 618knot** [comment]
これ、dummy_sheet.jsonの形式で本当に大丈夫？

**Comment by ItisNoMatter** [comment]
どの辺が不安ポイントですか

**Comment by 618knot** [comment]
- バス3本分の情報しかない
- 備考情報がない(timetable-parser側にもない)
- `"expiration_date"`の情報は現状timetable-parserからは送られない

**Comment by ItisNoMatter** [comment]
・バス3本分の情報しかない 
dummyの記述例は、3本分だけの情報が欲しいと言ってるわけではなく、リスト形式でn本のバスの情報が欲しい、と言ってるつもりでした　
・備考情報がない(timetable-parser側にもない)
備考って何が入るんでしたっけ　「〜までの運行」みたいなやつなら、発車時刻データの揃い方から判断できるか、と思っています
・"expiration_date"の情報は現状timetable-parserからは送られない
これはちょっと困るかも　フロントエンド側ではexpiration_dateに依存して新しい時刻表のリクエストを送るか判断するつもりでした

僕視点では最後の"expiration_date"の件だけ対応が必要かなと思いました
pdfをパースする時点でその情報を持ってくるのは難しそうですか。

**Comment by 618knot** [comment]
"expiration_date"は多分なんとかできます
備考は揃い方から判断できるとしても、jsonにはくっつけないかんじですか

**Comment by ItisNoMatter** [comment]
ありがたいです
備考の「〜までの運行」について、pdfパーサからすんなり取得できるなら確かにjsonにくっついてた方がフロントでも綺麗に処理かけそうですね

ただ、備考欄に入る文字列の制約が（僕は）わかっていないので、その辺の処理って大変じゃない？と思っているところです。例えば、「〜までの運行」以外にも「この時刻にはn本バスが来ます」みたいなのも備考欄に入ることがあった気がするので。

**Comment by 618knot** [comment]
この2つだけなんだと思ってた
![image](https://user-images.githubusercontent.com/82982400/226625403-31976b80-98ca-4cbe-9a30-b87be65b95eb.png)

**Comment by ItisNoMatter** [comment]
UIに反映させる予定はそのふたつだけでok（n本運行のデータは捨ててヨシ）

例としてこんなのが入ってくる場合がある
うまく捌いて行先の情報だけ抽出できそうだったらpdf-parser側で処理してjsonに含めてくれたほうが嬉しいんだけど、どう思う？

![Screenshot_2023-03-22-13-38-39-06_e2d5b3f32b79de1d45acd1fad96fbb0f](https://user-images.githubusercontent.com/41831807/226804128-87c218a5-b776-42d1-be45-fcbb4fcb5e86.jpg)

**Comment by 618knot** [comment]
@ItisNoMatter 
ちょっといろいろ面倒そうなのでこの話は明日集まるときで

**Comment by 618knot** [comment]
方針変更もあったので#35 でやります
