### ISSUE TITLE
bff/pdfManager.pyをtimetable-parserに移植する

### ISSUE THREAD

**Issue by Reo-Satooooo** [ItisNoMatter/cist-cat#32]
**概要**
pdfManager.pyをtimetable-parserに移植する

**目的**
issue27で実装したwebからpdfを取得するpdfManager.pyをtimetable-parserに移植し、pdfの取得からjson形式に整形する責務をtimetable-parserに一任する。
bff直下のファイルはモジュール間の連携を責務とし、その他の責務は別のモジュールに一任する構成とする。

**TODO**
1.pdfManager.pyをtimetable-parserへ移植する。
2.timetable-parser内のスクリプトを修正する。
3.動作確認(ディレクトリ内にPDFファイルは一つしか存在しない仕様とする)

**備考**
WebからPDFを取得する際にファイル名を直接指定するのではなく、Webページ上のファイルの位置を特定した上でファイル名に依存しない形式でPDFを取得するスクリプトに修正する。

**Comment by Reo-Satooooo** [comment]
@618knot 
timetable-parserのJSON周りのメソッド、クラスでまとめる形式に少し書き換えるね

**Comment by 618knot** [comment]
承知です〜

**Comment by Reo-Satooooo** [comment]
@618knot 
issue#27のブランチを閉じ忘れて、そのままこのissueの処理を始めてしまった。すまぬ...

**Comment by Reo-Satooooo** [comment]
@ItisNoMatter @618knot 
docker-compose up するとdummy_sheetのjsonが http://localhost:9000/ で取得できるようになってます。

ただ、timetable-parserのビルドが上手く走らない問題に直面中です。

具体的にはimportが上手く処理されない（パスの指定の問題？）、composeの設定ファイルが間違っているかもしれない（画像の出力を見るに、/app/app/main.pyというパスを探索するように設定されている気がする。そんな階層存在しないよなと...）

![スクリーンショット 2023-03-21 4 34 56](https://user-images.githubusercontent.com/69742127/226447100-85359ac1-59c6-42b5-9f85-942476c797c6.png)

**Comment by Reo-Satooooo** [comment]
とりあえず現状をリモートにpushした状態で手を止めてます

**Comment by 618knot** [comment]
@Reo-Satooooo 
サブモジュール側もpushしていただけますか？

**Comment by Reo-Satooooo** [comment]
@618knot 
以下のブランチをサブモジュール内で作成した上でpushしました。

（bff側と同時にサブモジュール側の変更をcommit/pushするとサブモジュール側では、ブランチがない状態でcommitログが溜まっていく仕様らしい。つまり、サブモジュール側は別にモジュール内でブランチを切ってbffに対する変更とは別にcommit/pushしないと事故る可能性が高いことが判明しました。今回は多分大丈夫です。）

動作確認するときは、サブモジュール内でブランチを移動してからやってみてください。

[fix_detached_HEAD](https://github.com/618knot/timetable-parser/tree/fix_detached_HEAD)

**Comment by 618knot** [comment]
@Reo-Satooooo 
import文の修正とrequirements.txtへの追加記述をすることで動作しました。
そのまま[fix_detached_HEAD](https://github.com/618knot/timetable-parser/tree/fix_detached_HEAD)にプッシュしてしまったので、pullして確認お願いします

**Comment by Reo-Satooooo** [comment]
@618knot 
pullしたらビルド走りました。
移植作業が一旦終了したのでプルリク出しますね。
細かな修正は、別にissueを立てます。

**Comment by Reo-Satooooo** [comment]
docker-compose -up はできる（サーバーの起動・各種設定ファイルの読み込み・ビルド）

けど、サブモジュールのhttp接続ができていないみたい

原因は調査中です

<img width="1045" alt="スクリーンショット 2023-03-22 15 43 11" src="https://user-images.githubusercontent.com/69742127/226823031-9de82279-85e2-4d71-a638-25c8927b70ef.png">

**Comment by 618knot** [comment]
@Reo-Satooooo 
マージ後の環境で `docker compose up` したら、こちらでは動いた(待機状態にはなった)のですが動きそうですか？
(証明書関係のエラーメッセージは出てきちゃいますが)

**Comment by Reo-Satooooo** [comment]
@618knot 
pullしてどうだ確認しました。
9000番ポートへアクセスするとdammy_jsonが返答され、8000番ポートにアクセスすると時刻表が整形されたものが返ってきます
<img width="856" alt="スクリーンショット 2023-03-24 3 46 47" src="https://user-images.githubusercontent.com/69742127/227317488-2fd62ca7-a1ef-42d8-b41e-2f61442ed177.png">
<img width="707" alt="スクリーンショット 2023-03-24 3 46 56" src="https://user-ima
![スクリーンショット 2023-03-24 3 47 11](https://user-images.githubusercontent.com/69742127/227317512-1676c02c-265e-48d5-be0c-00685d5adf2b.png)
ges.githubusercontent.com/69742127/227317495-b2e20c47-6cf9-41b4-b738-d934a26f237d.png">

**Comment by Reo-Satooooo** [comment]
このissueはクローズして、timetable-parserの機能をbffモジュールに持たせるissueを別途立てます。
