### ISSUE TITLE
デプロイ先の検討

### ISSUE THREAD

**Issue by Reo-Satooooo** [ItisNoMatter/cist-cat#33]
**概要**
バックエンドのプログラムをデプロイする先を検討する

**目的**
作成したプログラムをデプロイ（サーバー上で動作するように設定）し、フロントエンドのプログラムからアクセスできるようにする方法を調査する。

**TODO**
1.作成したプログラムの構造を理解する。
2.pythonプログラムのデプロイに対応したサーバーを調査する。

**Comment by Reo-Satooooo** [comment]
調査していただいた内容に基づいて、デプロイの作業進めますね。

**Comment by Kusunoki9999** [comment]
すみません、確認遅れました。
デプロイ先の比較・検討結果は[こちら](https://hackmd.io/@Kusunoki9999/B1RkLhJ-3)にまとめました。
ただ、自分なりにできる限りのリサーチは行ったつもりですが、まだまだ理解が足りてない部分や比較が至っていない部分が多くあると思われます。
まとめた内容について疑問や不安点、追加調査してほしい内容等あれば遠慮なく教えてください。

**Comment by Reo-Satooooo** [comment]
今回のデプロイ先はCloudRunとなりました。
終了したissueのためクローズします
