### ISSUE TITLE
timetable-parserが生成するJSONの形式を変更

### ISSUE THREAD

**Issue by 618knot** [ItisNoMatter/cist-cat#36]
**概要**
#35 
timetable-parserが返すJSONの形式を変更する
`new_jsonメソッド`の書き換え

**目的**
現状では不足している情報などがあるため
**TODO**
https://github.com/618knot/timetable-parser
1. timetable-parserの環境準備
    - `timetable-parser`のディレクトリに移動して`mainブランチ`からpullする
    - `timetable-parser/app`配下に`downloadフォルダ`を作る
    - 時刻表PDFをダウンロードしてきて、 `downloadフォルダ`の中に入れる
    - 何らかの方法で`JsonManagerクラス`の`new_jsonメソッド`を呼び、戻り値(JSON)を確認してみる
2. [要求されているJSONの形式を確認する](https://github.com/ItisNoMatter/cist-cat/issues/35#issuecomment-1492875232)
3. `jsonManager.py`内の`new_jsonメソッド`を書き換え、メソッドが要求されているJSON形式を返すようにする
場合によってはメソッドを増やしたり、新しくファイルを作ってもよい

**Comment by 618knot** [comment]
@Kusunoki9999 
こちらお願いできますか？
クラスベースのコードを読んだり、未知のコードを編集したりすることになると思うのでタスクとしては重いかもしれないです

**Comment by Kusunoki9999** [comment]
了解しました！
自分なりに出来る限りのことを頑張りたいと思います！

**Comment by Reo-Satooooo** [comment]
終了したissueのためクローズします
